# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - prod-ap-ms-order

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://prodcrmsordersystem.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3cf82af2fffe4d75a978df5e61fdb518 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5002bcf46fd14da29b4f320255212a59 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: prodcrmsordersystem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3cf82af2fffe4d75a978df5e61fdb518 }}/microserviceorder:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prod-ap-ms-order'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0110411b6a14fe6a611d026230159c0 }}
        images: 'prodcrmsordersystem.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3cf82af2fffe4d75a978df5e61fdb518 }}/microserviceorder:${{ github.sha }}'